### ISSUE TITLE
Website shows 'undefined' on various places.

### ISSUE THREAD

**Issue by neolite** [arguiot/ProType#3] opened 2018-05-22 14:27 UTC
[http://prntscr.com/jl63r9](http://prntscr.com/jl63r9)

**Comment by arguiot** [comment] 2018-05-22 14:30
Could you open the inspector or developer menu, and take a screenshot of the errors? It is certainly an error due to Glottologist, the library I use to translate the website

**Comment by neolite** [comment] 2018-05-22 14:52
![image](https://user-images.githubusercontent.com/576423/40370415-e730c51a-5de8-11e8-845f-c8f39a49c3a8.png)

**Comment by neolite** [comment] 2018-05-22 14:53
![image](https://user-images.githubusercontent.com/576423/40370500-0f0ddd84-5de9-11e8-99f7-2a538601d6a0.png)

**Comment by arguiot** [comment] 2018-05-22 14:54
But my intuition was good, Glottologist has a bug somewhere, and I'm going to fix it.

**Comment by arguiot** [comment] 2018-05-22 14:59
Good news, I'm able to reproduce the bug! I'm going to fix as soon as possible

**Comment by arguiot** [comment] 2018-05-23 01:47
@neolite  It should be fixed. Try and tell me if you're able to see the website as you should

**Closed by arguiot** 2018-05-23 01:47 UTC
